gary: 3
hairy: 4
dot: false
chives:
  spices: true
  love: 15
  "sore_losers": {
      "cool": "beans",
      // trailing commas and comments allowed
      /* so good */
      "state": "virginia",
  }
